### ISSUE TITLE
parselmouth.PraatError: Unknown variable:

### ISSUE THREAD

**Issue by codeundercoverdev** [Shahabks/my-voice-analysis#1]
This llibrary looks awesome!  I'm trying to repeat the first example locally.  

I created a folder called `my-voice-analysis/Mysp` and placed the `myspsolution.praat` file in that folder and a wav file called `about_time.wav` that is a 4 second clip of a man speaking. From the `my-voice-analysis` firectory, I try running:

```
mysp=__import__("my-voice-analysis")
p="about_time" # Audio File title
c = r"Mysp"
mysp.myspgend(p,c)
```

I get the following error:

```
>>> mysp.myspgend(p,c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/conda3/lib/python3.7/site-packages/my-voice-analysis/__init__.py", line 231, in myspgend
    objects= run_file(sourcerun, -20, 2, 0.3, "yes",sound,path, 80, 400, 0.01, capture_output=True)
parselmouth.PraatError: Unknown variable:
« (ln(f_one
Script line 295 not performed or completed:
« lnf0 = (ln(f_one)-5.65)/0.31 »
Script not completed.
```

Any idea?  Thanks!

**Comment by Shahabks** [comment]
Please put down the path to the directory as c=r"C:/user/.../myspsolution.praat"
another possibility, if your audio contents background noise the file won't be analysed.

Please let me know if you run again into problems.....I will fix the background noise problem and other fixations to make it easy to use

**Comment by Shahabks** [comment]
@codeundercoverdev 
Please put down the path to the directory as c=r"C:/user/.../myspsolution.praat"
another possibility, if your audio contents background noise the file won't be analysed.

I revised myspsolution.praat and my-voice-analysis at pypi ....please consider to download the formar one and upgrade you my-voice-analysis from pypi.

Please let me know if you run again into problems.....I will fix the background noise problem and other fixations to make it easy to use

**Comment by codeundercoverdev** [comment]
Hi @Shahabks , I am using a Mac, so there is no c drive.  The file should be targeted correctly with the code I have. Also, there is no background noise in the file.  Any ideas?

**Comment by codeundercoverdev** [comment]
oh, didn't see your second message. I'll try upgrading and let you know.

**Comment by Shahabks** [comment]
hi @codeundercoverdev 
I would suggest you add the following two line codes 

[in]
       my=__import__("my-voice-analysis")
       # Add the following two lines
       p=input("enter the path to the dataset:   ")     
                                  #then copy/paste   C:\Users\Desktop\dataset\
       m=input("enter the audio file name:    ")   # the audio fiile name without extention 

      my.mysppaus(m,p)
      my.myspsr(m,p)
      my.myspatc(m,p)
      my.myspst(m,p)
      my.myspod(m,p)
      my.myspbala(m,p)
      my.myspf0mean(m,p)
      my.myspf0sd(m,p)
     my.myspf0med(m,p)
     my.myspf0min(m,p)
     my.myspf0max(m,p)
    my.myspf0q25(m,p)
     my.myspf0q75(m,p)
     my.mysptotal(m,p)
     my.mysppron(m,p)
     my.myspgend(m,p)

[out] 
================= RESTART: C:\Users\ta\Desktop\myvoiceee.py =================
enter the path to the dataset:   C:\Users\ta\Desktop\testasr\dataset\audioFiles
enter the audio file name:    sound
[]
number_ of_syllables= 66
[]
number_of_pauses= 2
[]
rate_of_speech= 3 # syllables/sec original duration
[]
articulation_rate= 4 # syllables/sec speaking duration
[]
speaking_duration= 17.7 # sec only speaking duration without pauses
[]
original_duration= 19.6 # sec total speaking duration with pauses
[]
balance= 0.9 # ratio (speaking duration)/(original duration)
[]
f0_mean= 146.83 # Hz global mean of fundamental frequency distribution
[]
f0_SD= 18.95 # Hz global standard deviation of fundamental frequency distribution
[]
f0_MD= 145.0 # Hz global median of fundamental frequency distribution
[]
f0_min= 71 # Hz global minimum of fundamental frequency distribution
[]
f0_max= 237 # Hz global maximum of fundamental frequency distribution
[]
f0_quan25= 140 # Hz global 25th quantile of fundamental frequency distribution
[]
f0_quan75= 153 # Hz global 75th quantile of fundamental frequency distribution
[]
                           0
number_ of_syllables      66
number_of_pauses           2
rate_of_speech             3
articulation_rate          4
speaking_duration       17.7
original_duration       19.6
balance                  0.9
f0_mean               146.83
f0_std                 18.95
f0_median                145
f0_min                    71
f0_max                   237
f0_quantile25            140
f0_quan75                153
[]
Pronunciation_posteriori_probability_score_percentage= :89.96
[]
a Male, mood of speech: speaking passionately, p-value/sample size= :0.00 5
>>> 

NOTE: if the audio file is not clear you will see the following message
Try again the sound of the audio was not clear [the 3rd output]

I hope it works for you

**Comment by Shahabks** [comment]
@codeundercoverdev 
Hello Phil, have you tried the a/m algorithm? the issue fixed?
I would be grateful if you let me know your latest experience

**Comment by shiulee** [comment]
Getting an error
Below is my script
my=import("my-voice-analysis")
p=input("D:\Appshark\Projects\xxx")
m=input("D:\Appshark\Projects\xxx\25641692.wav") 
my.mysppaus(m,p)

  File "<ipython-input-21-d3dadc8468df>", line 1
    my=import("my-voice-analysis")
            ^
SyntaxError: invalid syntax

**Comment by Shahabks** [comment]
please rewrite your script as:
[in]
# after symbol "=" enter twice underline "__" and without any space, type
"import" and again without pace twice underline "__" and then
("my-voice-analysis")
my=__import__("my-voice-analysis")
p=input("Enter the path to the audio file:")
m=input("Enter the audio file name:")
ouut=my.mysppaus(m,p)
print(ouut)

after running the script the followings will pop out:
[out]
# your machine ask
Enter the path to the audio file: (please enter the path)
...D:\Appshark\Projects\xxx\
Enter the audio file name: (please enter the audio file name without
extension .wav)
... 25641692

that is it.

note: in some python versions you might need to get "input" command
differently. Please let me know if you run into error again.

**Comment by wjaubert** [comment]
Hi @Shahabks,  I am doing exactly what you have done up there but I cannot get pass through "Try again the sound of the audio was not clear". Is it linked to the quality of the file ? Although I doubt it because I use The Ryerson Audio-Visual Database of Emotional Speech and Song (RAVDESS) which are audio files of good quality.

**Comment by Shahabks** [comment]
Hello, could you please make sure

   1. the audio files are .wav.
   2. the length of recorded voice is 7 sec. +,
   3. Utterances without long fillers or very long pauses

If you still run into issues please let me have more information on the
issue to help you

**Comment by willianbs** [comment]
Same issue here, tried everything :/
Any updates on this @Shahabks or @wil2210 ?

**Comment by Shahabks** [comment]
could you please send me your code as well as the audio file you wish to
analyse? I check on it

**Comment by willianbs** [comment]
@Shahabks Here it is: https://www.dropbox.com/s/da97dh0jcwnip0s/voice-analysis.zip?dl=0

**Comment by Shahabks** [comment]
Sorry Will, my access to the dropbox of yours is denied ..... perhaps it
something about my system setup.......could you send them here, gmail

**Comment by willianbs** [comment]
@Shahabks Send failed. which e-mail? shahabks@gmail does not work :/

**Comment by willianbs** [comment]
Nevermind, reinstalled all and managed it to work :)
Thanks!
