### ISSUE TITLE
pronuntiation posteriori probability score percentage

### ISSUE THREAD

**Issue by Chivone** [Shahabks/my-voice-analysis#10]
I have a question, what exactly does the variable pronuntiation posteriori probability score percentage measure? The probability that that person will later pronounce as they do on the recording? 

Thank you very much,

**Comment by Shahabks** [comment]
this library "my-voice-analysis' is an abstract version of one module of one of our projects in the past. In the main project we employed speech recognition and it had a pronunciation-practice-module. This article may be of interest to you  "Liang W., Liu J., Liu R. (2004) Comparison of Pronunciation Scores in Spoken Language Learning System. In: Liu W., Shi Y., Li Q. (eds) Advances in Web-Based Learning – ICWL 2004. ICWL 2004. Lecture Notes in Computer Science, vol 3143. Springer, Berlin, Heidelberg. https://doi.org/10.1007/978-3-540-27859-7_56", .
