### ISSUE TITLE
Accessing the time stamps of filler words.

### ISSUE THREAD

**Issue by kan-cloud** [Shahabks/my-voice-analysis#12]
My understanding of the term filler words involves utterances such as 'umm' and 'uhh'. Is this what my-voice-analysis detects? I have been unable to access the timestamps of the filler words from the Textgrid file. Is there a way to access the timestamps of filler words that are distinct from pauses listed in the text grid file?

On a side note, I would like to thank you for your library.

**Comment by Shahabks** [comment]
you should define it in the praat script
