### ISSUE TITLE
Extracting the results from fucntions

### ISSUE THREAD

**Issue by ypirkani** [Shahabks/my-voice-analysis#13]
I am working on some audio files and getting the results. 
I am looking to save the results in a variable but unable to do so. 

eg. 

mysp=__import__("my-voice-analysis")
x = mysp.mysppaus(p,c)
print(x)

It returns:
[]
number_of_pauses= 72
None

How do I save the number 72 into the variable x.

**Comment by Shahabks** [comment]
I assume you have experienced using praat, so you can return the value from the praat script and then use Parselmouth (Praat in Python)
