### ISSUE TITLE
ModuleNotFoundError: No module named 'myspsolution'

### ISSUE THREAD

**Issue by yanqing5603691** [Shahabks/my-voice-analysis#3]
![image](https://user-images.githubusercontent.com/38271807/57686640-861b6a80-766c-11e9-9c9a-d7165b26d35f.png)
我想使用这个案例，在本地运行的时候找不到这个myspsolution，我已经下载了
![image](https://user-images.githubusercontent.com/38271807/57686735-b6630900-766c-11e9-95ce-de2eafc5c117.png)
请教一下出现这个问题的原因

**Comment by wajdilsa** [comment]
I Copied the content of __init__.py to my notebook and it works.

**Comment by yanqing5603691** [comment]
changed name then it works
