### ISSUE TITLE
import myspsolution as mysp is not working

### ISSUE THREAD

**Issue by llPekoll** [Shahabks/my-voice-analysis#5]
I can pip install `pip install my-voice-analysis`  
but then I can't `import myspsolution` since I don't have any myspsolution installed, the module is called -> my-voice-analysis .
This can work by taking the __init__.py file in the module -> `../python3.6/site-packages/my-voice-analysis/__init__.py` ;) copy this file in my working directory and renamed it myspsolution.py
as well it could in interesting to use os.path.join isntead of `sound=p+"/"+m+".wav"` to make this work better on linux or mac.
Anyways really nice module 🥇

**Comment by ecelkl** [comment]
Hello, 
I came across the same problem. I copied the init.py file and change it's name to myspsolution.py.  (I copied it under the init.py file. But I don't understand the part os.path.join
I am working on mac either.

**Comment by ngc2392** [comment]
@karley2 You don't need to worry about the os.path.join part. As long as you copied the init.py file from `site-packages/my-voice-analysis/__init__.py` and named it myspolution.py, you are good.
