### ISSUE TITLE
Try again the sound of the audio was not clear

### ISSUE THREAD

**Issue by mbcse** [Shahabks/my-voice-analysis#6]
its again and again saying this error

**Comment by ngc2392** [comment]
@mbcse, did you make sure that the file "myspsolution.praat" is in the directory where your audio files are at? I was getting the same exception and this is what solved it for me.

**Comment by mbcse** [comment]
Yes it is still saying audio not clear

**Comment by ecelkl** [comment]
I am getting the same error also:(

**Comment by ngc2392** [comment]
Can you post your code?

**Comment by mbcse** [comment]
mysp=__import__("my-voice-analysis")



    

    
    
p="demo" # Audio File title
c=r"C:\Users\HP\Desktop\foldert"

mysp.myspgend(p,c)
mysp.myspsyl(p,c)
mysp.mysppaus(p,c)
mysp.myspsr(p,c)
mysp.myspatc(p,c)
mysp.myspst(p,c)
mysp.myspod(p,c)
mysp.myspbala(p,c)
mysp.myspf0mean(p,c)
mysp.myspf0sd(p,c)
mysp.myspf0med(p,c)
mysp.myspf0min(p,c)
mysp.myspf0max(p,c)
mysp.myspf0q25(p,c)
mysp.myspf0q75(p,c)
mysp.mysppron(p,c)



can you tell me about the python version that suits best

**Comment by davidfreire** [comment]
I have been able to workaround this issue by changing the __init__.py code. For each function:

Chaged this:
    sound=p+"/"+m+".wav"
    sourcerun=p+"/myspsolution.praat"
    path=p+"/"

to this (be aware that myspsolution.praat may not be in the same folder as the .wav files):
    sound=p+"/"+m+".wav"
    sourcerun="myspsolution.praat" 
    path=p+"/"

I've been checking everything thorugh os:
    print(os.path.isfile(sourcerun))
    print(os.path.isfile(sound))

All the best,

David
