### ISSUE TITLE
Training and description for myspsolution.praat 

### ISSUE THREAD

**Issue by dpny518** [Shahabks/my-voice-analysis#8]
Can you provide details on how you made this and what its made up of?

**Comment by Shahabks** [comment]
These articles might be of interest to you
"Automatic scoring of non-native spontaneous speech in tests of spoken English", Speech Communication, Volume 51, Issue 10, October 2009, Pages 883-895
"A three-stage approach to the automated scoring of spontaneous spoken responses", Computer Speech & Language, Volume 25, Issue 2, April 2011, Pages 282-306
